version: '3.8'
services:
  app:
    container_name: app
    image: adai1ne/twitch-rewards:latest
    build: .
    tty: true
    ports:
      - '443:443'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro

  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '172.17.0.1:5432:5432'
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  app:
    driver: local
  db:
    driver: local
