version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - '443:443'
    depends_on:
      - db
    env_file:
      - .env.prod
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '172.17.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.prod
  local-db:
    container_name: local-db
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  db:
    driver: local
  local-db:
    driver: local
