name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        # Add the private key to the SSH agent
        echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Add the Droplet's host key to known_hosts to prevent SSH prompts
        ssh-keyscan ${{ vars.DO_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -vTi ~/.ssh/id_rsa ${{ secrets.DO_SSH_USER }}@${{ vars.DO_SSH_HOST }} << 'EOF'
        cd /var/www
        mkdir test
        EOF
